<?php
/**
 * Plugin Name: Aaron KR — Portfolio Importer (aaron.kr)
 * Description: Imports the JSON from aaron-kr-exporter.php.
 *              Uses a streaming JSON parser — never loads the full file into
 *              memory. Safe for 100MB+ exports.
 *              INSTALL ON: aaron.kr / lab.aaron.kr   DELETE AFTER: import done
 * Version: 1.2.0
 */

defined( 'ABSPATH' ) || exit;

// ════════════════════════════════════════════════════════════════════════════
// ADMIN PAGE
// ════════════════════════════════════════════════════════════════════════════

add_action( 'admin_menu', function () {
    add_management_page(
        'Import from aaron.kr JSON',
        '📥 Import from JSON',
        'manage_options',
        'aaron-kr-importer',
        'aaron_kr_importer_page'
    );
} );

function aaron_kr_importer_page(): void {
    if ( ! current_user_can( 'manage_options' ) ) wp_die( 'Not allowed.' );

    @set_time_limit( 600 );
    @ini_set( 'memory_limit', '512M' );

    $result  = null;
    $preview = null;

    // ── Handle upload ──────────────────────────────────────────────────────────
    if (
        isset( $_POST['aaron_kr_action'] ) &&
        wp_verify_nonce( $_POST['_wpnonce'] ?? '', 'aaron_kr_import' ) &&
        ! empty( $_FILES['import_file']['tmp_name'] )
    ) {
        $tmp      = $_FILES['import_file']['tmp_name'];
        $dry_run  = ( $_POST['aaron_kr_action'] === 'dry_run' );
        $real_run = ( $_POST['aaron_kr_action'] === 'import' );

        if ( $dry_run || $real_run ) {
            // Move uploaded file to a stable location so we can read it
            // without keeping it in RAM
            $upload_dir = wp_upload_dir();
            $dest       = $upload_dir['basedir'] . '/aaron-kr-import-tmp.json';

            if ( ! move_uploaded_file( $tmp, $dest ) ) {
                $result = [ 'error' => 'Could not move uploaded file. Check uploads directory permissions.' ];
            } else {
                $header  = aaron_kr_read_export_header( $dest );
                $result  = aaron_kr_stream_import( $dest, $dry_run );
                $result['header'] = $header;
                @unlink( $dest ); // delete the temp file when done
            }
        }
    }
    ?>
    <div class="wrap">
        <h1>📥 Import Portfolio from JSON</h1>
        <p>Upload the JSON file generated by the exporter on aaronsnowberger.com.
           The file is parsed post-by-post — 112MB+ files are handled safely.</p>

        <?php if ( isset( $result['error'] ) ) : ?>
            <div class="notice notice-error">
                <p><strong>Error:</strong> <?php echo esc_html( $result['error'] ); ?></p>
            </div>
        <?php endif; ?>

        <?php if ( $result && ! isset( $result['error'] ) ) : ?>
            <?php $dr = $result['dry_run']; ?>
            <div class="notice <?php echo $dr ? 'notice-info' : 'notice-success'; ?>">
                <p>
                    <strong><?php echo $dr ? 'Dry run complete.' : 'Import complete.'; ?></strong>
                    <?php echo (int) $result['created']; ?> <?php echo $dr ? 'would be created' : 'created'; ?>,
                    <?php echo (int) $result['skipped']; ?> skipped (already exist),
                    <?php echo (int) $result['image_ok']; ?> images <?php echo $dr ? 'ready' : 'uploaded'; ?>,
                    <?php echo (int) $result['image_fail']; ?> image <?php echo $result['image_fail'] === 1 ? 'issue' : 'issues'; ?>,
                    <?php echo (int) $result['errors']; ?> errors.
                    <?php if ( $result['header'] ) : ?>
                        Source: <code><?php echo esc_html( $result['header']['source_site'] ?? '' ); ?></code>
                        &mdash; <?php echo (int) ( $result['header']['post_count'] ?? 0 ); ?> posts in file.
                    <?php endif; ?>
                </p>
            </div>

            <?php if ( ! empty( $result['log'] ) ) : ?>
                <details <?php echo $dr ? 'open' : ''; ?> style="margin:1rem 0">
                    <summary style="cursor:pointer;font-weight:600">
                        <?php echo $dr ? 'Preview' : 'Detail log'; ?>
                        (<?php echo count( $result['log'] ); ?> entries)
                    </summary>
                    <table class="widefat" style="margin-top:.75rem;max-width:100%">
                        <thead><tr>
                            <th>Post / Slug</th>
                            <th>Action</th>
                            <th>Image</th>
                            <th>Tags</th>
                            <th>Type terms</th>
                        </tr></thead>
                        <tbody>
                        <?php foreach ( $result['log'] as $row ) : ?>
                            <tr>
                                <td>
                                    <?php if ( ! empty( $row['post_id'] ) ) : ?>
                                        <a href="<?php echo esc_url( get_edit_post_link( $row['post_id'] ) ); ?>">
                                            <?php echo esc_html( $row['title'] ); ?>
                                        </a>
                                    <?php else : ?>
                                        <?php echo esc_html( $row['title'] ); ?>
                                    <?php endif; ?>
                                    <br><small style="color:#999">
                                        <code><?php echo esc_html( $row['slug'] ); ?></code>
                                    </small>
                                </td>
                                <td><?php echo esc_html( $row['action'] ); ?></td>
                                <td style="font-size:12px"><?php echo esc_html( $row['image'] ); ?></td>
                                <td style="font-size:11px"><?php echo esc_html( implode( ', ', $row['tags'] ) ); ?></td>
                                <td style="font-size:11px"><?php echo esc_html( implode( ', ', $row['type_terms'] ) ); ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </details>
            <?php endif; ?>

            <?php if ( $dr ) : ?>
                <div style="margin-top:1.25rem;padding:1rem;background:#e7f5fe;border-left:4px solid #007cba">
                    <p>↑ Dry run — nothing written. Re-upload and click
                    <strong>Run Real Import</strong> when ready.</p>
                </div>
            <?php else : ?>
                <div style="margin-top:1.25rem;padding:1rem;background:#fff3cd;border-left:4px solid #ffc107">
                    <p><strong>🗑 Now delete this file:</strong>
                       <code>wp-content/mu-plugins/aaron-kr-importer.php</code></p>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <hr style="margin:2rem 0">

        <form method="post" enctype="multipart/form-data" style="max-width:680px">
            <?php wp_nonce_field( 'aaron_kr_import' ); ?>

            <table class="form-table">
                <tr>
                    <th scope="row"><label for="import_file">JSON export file</label></th>
                    <td>
                        <input type="file" name="import_file" id="import_file"
                               accept=".json,application/json" required>
                        <p class="description">
                            The file generated by the exporter on aaronsnowberger.com.
                            Large files (100MB+) are handled safely.
                        </p>
                    </td>
                </tr>
            </table>

            <p class="submit" style="display:flex;gap:1rem;flex-wrap:wrap">
                <button type="submit" name="aaron_kr_action" value="dry_run"
                        class="button button-large">
                    🔍 Dry Run (preview only)
                </button>
                <button type="submit" name="aaron_kr_action" value="import"
                        class="button button-primary button-large"
                        onclick="return confirm('Run the real import? Existing posts (matched by slug) will be skipped.')">
                    📥 Run Real Import
                </button>
            </p>
        </form>
    </div>
    <?php
}

// ════════════════════════════════════════════════════════════════════════════
// READ EXPORT HEADER
// Reads only the first few KB to extract metadata — never loads the full file.
// ════════════════════════════════════════════════════════════════════════════

function aaron_kr_read_export_header( string $path ): array {
    $fp   = fopen( $path, 'rb' );
    $head = fread( $fp, 4096 ); // first 4KB is plenty for header fields
    fclose( $fp );

    $fields = [];
    foreach ( [ 'export_version', 'export_date', 'source_site',
                'source_type', 'target_type', 'post_count' ] as $key ) {
        if ( preg_match( '/"' . $key . '"\s*:\s*"?([^",}\]]+)"?/', $head, $m ) ) {
            $fields[ $key ] = trim( $m[1], '"' );
        }
    }
    return $fields;
}

// ════════════════════════════════════════════════════════════════════════════
// STREAMING JSON PARSER + IMPORT
// Reads the file in 64KB chunks. Uses a character-level state machine to
// identify complete post objects ({...}) one at a time, json_decodes each
// individually, processes it, then frees memory before reading the next.
// Peak memory = size of one post object, not the whole file.
// ════════════════════════════════════════════════════════════════════════════

function aaron_kr_stream_import( string $path, bool $dry_run ): array {
    // Media upload helpers — needed for sideload
    require_once ABSPATH . 'wp-admin/includes/media.php';
    require_once ABSPATH . 'wp-admin/includes/file.php';
    require_once ABSPATH . 'wp-admin/includes/image.php';

    $created    = 0;
    $skipped    = 0;
    $errors     = 0;
    $image_ok   = 0;
    $image_fail = 0;
    $log        = [];

    $fp = fopen( $path, 'rb' );
    if ( ! $fp ) {
        return [ 'error' => 'Cannot open uploaded file for reading.' ];
    }

    // ── State machine variables ────────────────────────────────────────────────
    $state    = 'seeking';  // seeking | between | in_post
    $buf      = '';         // accumulates the current post's JSON text
    $head_buf = '';         // small buffer used only during 'seeking'
    $depth    = 0;          // brace nesting depth
    $in_str   = false;      // are we inside a JSON string?
    $esc      = false;      // did we just see a backslash inside a string?

    // ── Read file in chunks ────────────────────────────────────────────────────
    while ( ! feof( $fp ) ) {
        $chunk = fread( $fp, 65536 ); // 64 KB at a time
        $len   = strlen( $chunk );

        for ( $i = 0; $i < $len; $i++ ) {
            $c = $chunk[ $i ];

            // ── SEEKING: scan forward until we find "posts":[ ─────────────────
            if ( $state === 'seeking' ) {
                $head_buf .= $c;
                // Only keep the last 20 chars — enough to match our marker
                if ( strlen( $head_buf ) > 20 ) {
                    $head_buf = substr( $head_buf, -20 );
                }
                if ( str_ends_with( $head_buf, '"posts":[' ) ) {
                    $state    = 'between';
                    $head_buf = '';
                }
                continue;
            }

            // ── BETWEEN: skip commas/whitespace, wait for next { ──────────────
            if ( $state === 'between' ) {
                if ( $c === '{' ) {
                    $state  = 'in_post';
                    $buf    = '{';
                    $depth  = 1;
                    $in_str = false;
                    $esc    = false;
                }
                // ignore ',' ']' '}' whitespace between posts
                continue;
            }

            // ── IN_POST: accumulate characters, track string/brace context ─────
            if ( $state === 'in_post' ) {
                $buf .= $c;

                if ( $esc ) {
                    $esc = false;
                    continue;
                }
                if ( $c === '\\' && $in_str ) {
                    $esc = true;
                    continue;
                }
                if ( $c === '"' ) {
                    $in_str = ! $in_str;
                    continue;
                }
                if ( $in_str ) continue; // content of a string — not structural

                if ( $c === '{' ) {
                    $depth++;
                } elseif ( $c === '}' ) {
                    $depth--;
                    if ( $depth === 0 ) {
                        // ── Complete post object ──────────────────────────────
                        $post = json_decode( $buf, true );
                        $buf  = ''; // free memory immediately
                        $state = 'between';

                        if ( ! is_array( $post ) ) {
                            $errors++;
                            continue;
                        }

                        // Process this post
                        $row = aaron_kr_import_one( $post, $dry_run );
                        $log[] = $row;

                        if ( $row['action'] === 'created' )         $created++;
                        elseif ( $row['action'] === 'skipped' )     $skipped++;
                        elseif ( str_starts_with( $row['action'], 'ERROR' ) ) $errors++;

                        if ( str_starts_with( $row['image'], '✓' ) ) $image_ok++;
                        elseif ( str_starts_with( $row['image'], '✗' ) ) $image_fail++;

                        unset( $post, $row );
                    }
                }
            }
        }
    }

    fclose( $fp );

    return compact( 'created', 'skipped', 'errors', 'image_ok', 'image_fail', 'log', 'dry_run' );
}

// ════════════════════════════════════════════════════════════════════════════
// IMPORT ONE POST
// ════════════════════════════════════════════════════════════════════════════

function aaron_kr_import_one( array $item, bool $dry_run ): array {
    $title       = $item['post_title']   ?? '(untitled)';
    $slug        = sanitize_title( $item['post_name'] ?: $item['post_title'] );
    $target_type = $item['post_type']    ?? 'portfolio';

    // ── Duplicate check by slug ────────────────────────────────────────────────
    $existing = get_page_by_path( $slug, OBJECT, $target_type );
    if ( $existing ) {
        return [
            'title'     => $title, 'slug' => $slug,
            'action'    => 'skipped', 'post_id' => $existing->ID,
            'image'     => '—', 'tags' => [], 'type_terms' => [],
        ];
    }

    // ── Dry run: report what would happen, don't write ────────────────────────
    if ( $dry_run ) {
        $has_img    = ! empty( $item['featured_image_base64']['data'] ) ||
                      ! empty( $item['featured_image_url'] );
        $tags       = array_column( $item['jp_tags']       ?? [], 'name' );
        $type_terms = array_column( $item['jp_type_terms'] ?? [], 'name' );
        return [
            'title'     => $title, 'slug' => $slug,
            'action'    => 'would create', 'post_id' => null,
            'image'     => $has_img ? 'would upload' : 'no image',
            'tags'      => $tags, 'type_terms' => $type_terms,
        ];
    }

    // ── Create the post ────────────────────────────────────────────────────────
    $post_id = wp_insert_post( [
        'post_title'    => $title,
        'post_content'  => $item['post_content']  ?? '',
        'post_excerpt'  => $item['post_excerpt']  ?? '',
        'post_status'   => $item['post_status']   ?? 'draft',
        'post_date'     => $item['post_date']      ?? '',
        'post_date_gmt' => $item['post_date_gmt']  ?? '',
        'post_name'     => $slug,
        'post_type'     => $target_type,
        'menu_order'    => (int) ( $item['menu_order'] ?? 0 ),
    ], true );

    if ( is_wp_error( $post_id ) ) {
        return [
            'title'  => $title, 'slug' => $slug,
            'action' => 'ERROR: ' . $post_id->get_error_message(),
            'post_id'=> null, 'image' => '—',
            'tags'   => [], 'type_terms' => [],
        ];
    }

    // ── Post meta ─────────────────────────────────────────────────────────────
    foreach ( $item['post_meta'] ?? [] as $k => $v ) {
        update_post_meta( $post_id, $k, $v );
    }

    // ── Tags: jp_tags + std_tags → post_tag ───────────────────────────────────
    $tag_names = array_unique( array_merge(
        array_column( $item['jp_tags']  ?? [], 'name' ),
        array_column( $item['std_tags'] ?? [], 'name' )
    ) );
    if ( $tag_names ) {
        wp_set_post_terms( $post_id, $tag_names, 'post_tag', false );
    }

    // ── Type terms → portfolio_type ───────────────────────────────────────────
    $type_terms = array_column( $item['jp_type_terms'] ?? [], 'name' );
    if ( $type_terms && taxonomy_exists( 'portfolio_type' ) ) {
        foreach ( $type_terms as $tn ) {
            if ( ! term_exists( $tn, 'portfolio_type' ) ) {
                wp_insert_term( $tn, 'portfolio_type' );
            }
        }
        wp_set_object_terms( $post_id, $type_terms, 'portfolio_type', false );
    }

    // ── Categories ────────────────────────────────────────────────────────────
    $cat_ids = [];
    foreach ( array_column( $item['categories'] ?? [], 'name' ) as $cn ) {
        $cat = get_category_by_slug( sanitize_title( $cn ) );
        if ( $cat ) {
            $cat_ids[] = $cat->term_id;
        } else {
            $new = wp_insert_term( $cn, 'category' );
            if ( ! is_wp_error( $new ) ) $cat_ids[] = $new['term_id'];
        }
    }
    if ( $cat_ids ) wp_set_post_categories( $post_id, $cat_ids );

    // ── Featured image ────────────────────────────────────────────────────────
    $img_status = 'no image';
    $b64        = $item['featured_image_base64'] ?? null;

    if ( ! empty( $b64['data'] ) && ! empty( $b64['mime'] ) ) {
        $img_status = aaron_kr_sideload_b64(
            $post_id,
            $b64['data'],
            $b64['mime'],
            $item['featured_image_filename'] ?? 'image.jpg',
            $item['featured_image_alt']      ?? $title
        );
    } elseif ( ! empty( $item['featured_image_url'] ) ) {
        $img_status = aaron_kr_sideload_url(
            $post_id,
            $item['featured_image_url'],
            $item['featured_image_alt'] ?? $title
        );
    }

    return [
        'title'      => $title, 'slug' => $slug,
        'action'     => 'created', 'post_id' => $post_id,
        'image'      => $img_status,
        'tags'       => $tag_names,
        'type_terms' => $type_terms,
    ];
}

// ════════════════════════════════════════════════════════════════════════════
// IMAGE SIDELOADERS
// ════════════════════════════════════════════════════════════════════════════

function aaron_kr_sideload_b64(
    int $pid, string $b64, string $mime, string $filename, string $alt
): string {
    $tmp = wp_tempnam( $filename );
    $ok  = file_put_contents( $tmp, base64_decode( $b64 ) );
    if ( $ok === false ) {
        @unlink( $tmp );
        return '✗ could not write temp file';
    }

    $file   = [ 'name' => $filename, 'tmp_name' => $tmp, 'type' => $mime,
                'error' => UPLOAD_ERR_OK, 'size' => filesize( $tmp ) ];
    $att_id = media_handle_sideload( $file, $pid, $alt );
    @unlink( $tmp );

    if ( is_wp_error( $att_id ) ) return '✗ ' . $att_id->get_error_message();
    if ( $alt ) update_post_meta( $att_id, '_wp_attachment_image_alt', $alt );
    set_post_thumbnail( $pid, $att_id );
    return '✓ uploaded';
}

function aaron_kr_sideload_url( int $pid, string $url, string $alt ): string {
    // Strip Jetpack CDN prefix
    $src = (string) preg_replace( '#^https?://i\d+\.wp\.com/#', 'https://', $url );
    foreach ( [ $src, $url ] as $try ) {
        $tmp = download_url( $try, 30 );
        if ( is_wp_error( $tmp ) ) continue;

        $file   = [ 'name' => basename( (string) parse_url( $try, PHP_URL_PATH ) ),
                    'tmp_name' => $tmp ];
        $att_id = media_handle_sideload( $file, $pid, $alt );
        @unlink( $tmp );

        if ( is_wp_error( $att_id ) ) continue;
        if ( $alt ) update_post_meta( $att_id, '_wp_attachment_image_alt', $alt );
        set_post_thumbnail( $pid, $att_id );
        return '✓ from URL';
    }
    return '✗ URL fetch failed';
}
