<?php
/**
 * Plugin Name: Aaron KR — Portfolio Importer (aaron.kr)
 * Description: Imports the JSON produced by aaron-kr-exporter.php.
 *              Creates posts with correct custom post types, assigns taxonomy
 *              terms, uploads featured images to the correct uploads directory
 *              (https://files.aaron.kr/media/), and skips duplicates by slug.
 *              INSTALL ON: aaron.kr / lab.aaron.kr (the TARGET site)
 *              DELETE AFTER: import is complete
 * Version: 1.0.0
 */

defined( 'ABSPATH' ) || exit;

add_action( 'admin_menu', function () {
    add_management_page(
        'Import from aaron.kr JSON',
        '📥 Import from JSON',
        'manage_options',
        'aaron-kr-importer',
        'aaron_kr_importer_page'
    );
} );

function aaron_kr_importer_page(): void {
    if ( ! current_user_can( 'manage_options' ) ) wp_die( 'Not allowed.' );

    $result  = null;
    $preview = null;

    // ── Run import ─────────────────────────────────────────────────────────────
    if (
        isset( $_POST['aaron_kr_do_import'] ) &&
        wp_verify_nonce( $_POST['_wpnonce'], 'aaron_kr_import' ) &&
        ! empty( $_FILES['import_file']['tmp_name'] )
    ) {
        $json = file_get_contents( $_FILES['import_file']['tmp_name'] );
        $data = json_decode( $json, true );

        if ( ! $data || ! isset( $data['posts'] ) ) {
            $result = [ 'error' => 'Invalid JSON file — could not parse.' ];
        } else {
            $dry_run = ! empty( $_POST['dry_run'] );
            $result  = aaron_kr_run_import( $data, $dry_run );
        }
    }

    // ── Preview uploaded file without importing ────────────────────────────────
    if (
        isset( $_POST['aaron_kr_preview'] ) &&
        wp_verify_nonce( $_POST['_wpnonce'], 'aaron_kr_import' ) &&
        ! empty( $_FILES['import_file']['tmp_name'] )
    ) {
        $json    = file_get_contents( $_FILES['import_file']['tmp_name'] );
        $data    = json_decode( $json, true );
        $preview = $data ?? [ 'error' => 'Invalid JSON' ];
    }

    ?>
    <div class="wrap">
        <h1>📥 Import Portfolio from JSON</h1>
        <p>Upload the JSON file generated by the exporter on aaronsnowberger.com.
           Posts are identified by slug — existing posts with matching slugs are
           <strong>skipped</strong> (no overwrites). Run in dry-run mode first to
           preview what will happen.</p>

        <?php if ( isset( $result['error'] ) ) : ?>
            <div class="notice notice-error"><p><?php echo esc_html( $result['error'] ); ?></p></div>
        <?php endif; ?>

        <?php if ( $result && ! isset( $result['error'] ) ) : ?>
            <div class="notice notice-success">
                <p><strong><?php echo $result['dry_run'] ? 'Dry run complete.' : 'Import complete.'; ?></strong>
                   <?php echo (int) $result['created']; ?> created,
                   <?php echo (int) $result['skipped']; ?> skipped (already exist),
                   <?php echo (int) $result['errors']; ?> errors.</p>
            </div>
            <h2>Detail log</h2>
            <table class="widefat" style="max-width:900px">
                <thead><tr>
                    <th>Post</th><th>Status</th><th>Image</th><th>Tags</th><th>Type terms</th>
                </tr></thead>
                <tbody>
                <?php foreach ( $result['log'] as $row ) : ?>
                    <tr>
                        <td>
                            <?php if ( $row['post_id'] ) : ?>
                                <a href="<?php echo esc_url( get_edit_post_link( $row['post_id'] ) ); ?>">
                                    <?php echo esc_html( $row['title'] ); ?>
                                </a>
                            <?php else : ?>
                                <?php echo esc_html( $row['title'] ); ?>
                            <?php endif; ?>
                            <br><small><code><?php echo esc_html( $row['slug'] ); ?></code></small>
                        </td>
                        <td><?php echo $row['dry_run'] ? '🔍 (dry run)' : esc_html( $row['action'] ); ?></td>
                        <td><?php echo esc_html( $row['image_status'] ); ?></td>
                        <td><small><?php echo esc_html( implode( ', ', $row['tags'] ?? [] ) ); ?></small></td>
                        <td><small><?php echo esc_html( implode( ', ', $row['type_terms'] ?? [] ) ); ?></small></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <?php if ( $result['dry_run'] ) : ?>
                <p style="margin-top:1rem">
                    ↑ This was a dry run. Nothing was written to the database.
                    Re-upload the file and uncheck "Dry run" to perform the real import.
                </p>
            <?php else : ?>
                <p style="margin-top:1.5rem;padding:1rem;background:#fff3cd;border-left:4px solid #ffc107">
                    <strong>🗑 Delete this file</strong> now:
                    <code>wp-content/mu-plugins/aaron-kr-importer.php</code>
                </p>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ( $preview && ! isset( $preview['error'] ) ) : ?>
            <h2>File preview</h2>
            <p>Source: <code><?php echo esc_html( $preview['source_site'] ?? '?' ); ?></code>
               | Type: <code><?php echo esc_html( $preview['source_type'] ?? '?' ); ?></code>
               → <code><?php echo esc_html( $preview['target_type'] ?? '?' ); ?></code>
               | Posts: <strong><?php echo (int) ( $preview['post_count'] ?? 0 ); ?></strong>
               | Exported: <?php echo esc_html( $preview['export_date'] ?? '?' ); ?>
            </p>
        <?php endif; ?>

        <hr>

        <form method="post" enctype="multipart/form-data">
            <?php wp_nonce_field( 'aaron_kr_import' ); ?>

            <table class="form-table">
                <tr>
                    <th><label for="import_file">JSON export file</label></th>
                    <td>
                        <input type="file" name="import_file" id="import_file"
                               accept=".json,application/json" required>
                        <p class="description">Upload the file from the exporter on aaronsnowberger.com.</p>
                    </td>
                </tr>
                <tr>
                    <th><label for="dry_run">Dry run</label></th>
                    <td>
                        <label>
                            <input type="checkbox" name="dry_run" id="dry_run" value="1" checked>
                            Preview only — don't write anything to the database
                        </label>
                    </td>
                </tr>
            </table>

            <p class="submit" style="display:flex;gap:1rem;align-items:center">
                <button type="submit" name="aaron_kr_preview" value="1" class="button">
                    🔍 Preview file
                </button>
                <button type="submit" name="aaron_kr_do_import" value="1"
                        class="button button-primary button-large"
                        onclick="return confirm('Run import? Dry run is safe; real import creates posts.')">
                    📥 Run Import
                </button>
            </p>
        </form>
    </div>
    <?php
}

// ── Main import logic ─────────────────────────────────────────────────────────
function aaron_kr_run_import( array $data, bool $dry_run ): array {
    $log          = [];
    $created      = 0;
    $skipped      = 0;
    $errors       = 0;
    $target_type  = $data['target_type'] ?? 'portfolio';

    // Ensure media functions are available
    require_once ABSPATH . 'wp-admin/includes/media.php';
    require_once ABSPATH . 'wp-admin/includes/file.php';
    require_once ABSPATH . 'wp-admin/includes/image.php';

    foreach ( $data['posts'] as $item ) {
        $slug  = sanitize_title( $item['post_name'] ?: $item['post_title'] );
        $title = $item['post_title'];

        // ── Check for duplicate by slug ───────────────────────────────────────
        $existing = get_page_by_path( $slug, OBJECT, $target_type );
        if ( $existing ) {
            $log[] = [
                'title'        => $title,
                'slug'         => $slug,
                'action'       => 'skipped — already exists',
                'post_id'      => $existing->ID,
                'image_status' => '—',
                'tags'         => [],
                'type_terms'   => [],
                'dry_run'      => $dry_run,
            ];
            $skipped++;
            continue;
        }

        if ( $dry_run ) {
            $tags       = array_column( $item['jp_tags']       ?? [], 'name' );
            $type_terms = array_column( $item['jp_type_terms'] ?? [], 'name' );
            $has_image  = ! empty( $item['featured_image_base64']['data'] ) || ! empty( $item['featured_image_url'] );
            $log[] = [
                'title'        => $title,
                'slug'         => $slug,
                'action'       => 'would create',
                'post_id'      => null,
                'image_status' => $has_image ? 'would upload' : 'no image',
                'tags'         => $tags,
                'type_terms'   => $type_terms,
                'dry_run'      => true,
            ];
            $created++;
            continue;
        }

        // ── Create the post ───────────────────────────────────────────────────
        $post_id = wp_insert_post( [
            'post_title'    => $title,
            'post_content'  => $item['post_content']  ?? '',
            'post_excerpt'  => $item['post_excerpt']  ?? '',
            'post_status'   => $item['post_status']   ?? 'draft',
            'post_date'     => $item['post_date']      ?? '',
            'post_date_gmt' => $item['post_date_gmt']  ?? '',
            'post_name'     => $slug,
            'post_type'     => $target_type,
            'menu_order'    => $item['menu_order']     ?? 0,
        ], true );

        if ( is_wp_error( $post_id ) ) {
            $log[] = [
                'title'        => $title,
                'slug'         => $slug,
                'action'       => 'ERROR: ' . $post_id->get_error_message(),
                'post_id'      => null,
                'image_status' => '—',
                'tags'         => [],
                'type_terms'   => [],
                'dry_run'      => false,
            ];
            $errors++;
            continue;
        }

        // ── Post meta ─────────────────────────────────────────────────────────
        foreach ( $item['post_meta'] ?? [] as $key => $value ) {
            update_post_meta( $post_id, $key, $value );
        }

        // ── Taxonomy terms ────────────────────────────────────────────────────
        $tags_added       = [];
        $type_terms_added = [];

        // jp_tags → post_tag
        $tag_names = array_column( $item['jp_tags'] ?? [], 'name' );
        // Also merge any standard tags that were already on the post
        $tag_names = array_unique( array_merge(
            $tag_names,
            array_column( $item['std_tags'] ?? [], 'name' )
        ) );
        if ( $tag_names ) {
            wp_set_post_terms( $post_id, $tag_names, 'post_tag', false );
            $tags_added = $tag_names;
        }

        // jp_type_terms → portfolio_type (create terms if they don't exist)
        $type_names = array_column( $item['jp_type_terms'] ?? [], 'name' );
        if ( $type_names && taxonomy_exists( 'portfolio_type' ) ) {
            foreach ( $type_names as $tn ) {
                if ( ! term_exists( $tn, 'portfolio_type' ) ) {
                    wp_insert_term( $tn, 'portfolio_type' );
                }
            }
            wp_set_object_terms( $post_id, $type_names, 'portfolio_type', false );
            $type_terms_added = $type_names;
        }

        // Categories
        $cat_names = array_column( $item['categories'] ?? [], 'name' );
        if ( $cat_names ) {
            $cat_ids = [];
            foreach ( $cat_names as $cn ) {
                $cat = get_category_by_slug( sanitize_title( $cn ) );
                if ( $cat ) {
                    $cat_ids[] = $cat->term_id;
                } else {
                    $new = wp_insert_term( $cn, 'category' );
                    if ( ! is_wp_error( $new ) ) $cat_ids[] = $new['term_id'];
                }
            }
            if ( $cat_ids ) wp_set_post_categories( $post_id, $cat_ids );
        }

        // ── Featured image ────────────────────────────────────────────────────
        $image_status = 'no image in export';
        $img          = $item['featured_image_base64'] ?? null;

        if ( $img && ! empty( $img['data'] ) && $img['mime'] ) {
            // Base64 embedded image — decode and sideload
            $status = aaron_kr_sideload_base64(
                $post_id,
                $img['data'],
                $img['mime'],
                $item['featured_image_filename'] ?? 'image.jpg',
                $item['featured_image_alt'] ?? $title
            );
            $image_status = $status['message'];

        } elseif ( ! empty( $item['featured_image_url'] ) ) {
            // No base64 — try to sideload from URL directly
            $status = aaron_kr_sideload_url(
                $post_id,
                $item['featured_image_url'],
                $item['featured_image_alt'] ?? $title
            );
            $image_status = $status['message'];
        }

        $log[] = [
            'title'        => $title,
            'slug'         => $slug,
            'action'       => 'created',
            'post_id'      => $post_id,
            'image_status' => $image_status,
            'tags'         => $tags_added,
            'type_terms'   => $type_terms_added,
            'dry_run'      => false,
        ];
        $created++;
    }

    return compact( 'created', 'skipped', 'errors', 'log', 'dry_run' );
}

// ── Sideload a base64-encoded image ───────────────────────────────────────────
function aaron_kr_sideload_base64(
    int $post_id, string $b64, string $mime, string $filename, string $alt
): array {
    // Write to a temp file
    $tmp = wp_tempnam( $filename );
    file_put_contents( $tmp, base64_decode( $b64 ) );

    $file_array = [
        'name'     => $filename,
        'tmp_name' => $tmp,
        'type'     => $mime,
        'error'    => UPLOAD_ERR_OK,
        'size'     => filesize( $tmp ),
    ];

    $attach_id = media_handle_sideload( $file_array, $post_id, $alt );
    @unlink( $tmp );

    if ( is_wp_error( $attach_id ) ) {
        return [ 'ok' => false, 'message' => '✗ ' . $attach_id->get_error_message() ];
    }

    if ( $alt ) update_post_meta( $attach_id, '_wp_attachment_image_alt', $alt );
    set_post_thumbnail( $post_id, $attach_id );
    return [ 'ok' => true, 'message' => '✓ uploaded (base64)' ];
}

// ── Sideload from URL ─────────────────────────────────────────────────────────
function aaron_kr_sideload_url( int $post_id, string $url, string $alt ): array {
    // Strip Jetpack CDN prefix (i0.wp.com/...) to get the source URL
    $clean_url = preg_replace( '#^https://i\d+\.wp\.com/#', 'https://', $url );

    $tmp = download_url( $clean_url, 30 );
    if ( is_wp_error( $tmp ) ) {
        // Try original URL as fallback
        $tmp = download_url( $url, 30 );
        if ( is_wp_error( $tmp ) ) {
            return [ 'ok' => false, 'message' => '✗ URL fetch failed' ];
        }
    }

    $file_array = [
        'name'     => basename( parse_url( $clean_url, PHP_URL_PATH ) ),
        'tmp_name' => $tmp,
    ];

    $attach_id = media_handle_sideload( $file_array, $post_id, $alt );
    @unlink( $tmp );

    if ( is_wp_error( $attach_id ) ) {
        return [ 'ok' => false, 'message' => '✗ ' . $attach_id->get_error_message() ];
    }

    if ( $alt ) update_post_meta( $attach_id, '_wp_attachment_image_alt', $alt );
    set_post_thumbnail( $post_id, $attach_id );
    return [ 'ok' => true, 'message' => '✓ uploaded (URL)' ];
}
